import { manrope } from "@/lib/fonts";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="dark"
      className={`${manrope.className}  dark h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-black">
        <main>{children}</main>
      </body>
    </html>
  );
}
